development:
  database: travis_development
  adapter: postgresql
  encoding: unicode
  pool: 5
  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  min_messages: warning

production:
  database: travis_production
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning

jasmine:
  database: travis_jasmine
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning

test:
  database: travis_test
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning

cucumber:
  database: travis_test
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning

